## Обработка данных

In [1]:
import pandas as pd
df = pd.read_csv('data/users_behavior.csv')


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3214 entries, 0 to 3213
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   calls     3214 non-null   float64
 1   minutes   3214 non-null   float64
 2   messages  3214 non-null   float64
 3   mb_used   3214 non-null   float64
 4   is_ultra  3214 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 125.7 KB


In [4]:
df.describe()

,calls,minutes,messages,mb_used,is_ultra
count,3214.000000,3214.000000,3214.000000,3214.000000,3214.000000
mean,63.038892,438.208787,38.281269,17207.673836,0.306472
std,33.236368,234.569872,36.148326,7570.968246,0.461100
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,40.000000,274.575000,9.000000,12491.902500,0.000000
50%,62.000000,430.600000,30.000000,16943.235000,0.000000
75%,82.000000,571.927500,57.000000,21424.700000,1.000000
max,244.000000,1632.060000,224.000000,49745.730000,1.000000


In [5]:
df['is_ultra'].value_counts(normalize=True)

is_ultra
0    0.693528
1    0.306472
Name: proportion, dtype: float64

In [6]:
df_train, df_valid = train_test_split(df, test_size = 0.2, random_state =12345, stratify = df['is_ultra'])

In [7]:
df_train, df_test  = train_test_split(df_train, test_size = 0.25, random_state = 12345, stratify =  df_train['is_ultra'])

In [8]:
df_train.shape

(1928, 5)

In [9]:
df_test.shape

(643, 5)

In [10]:
df_valid.shape

(643, 5)

In [11]:
features = df_train.drop('is_ultra', axis = 1)
target = df_train['is_ultra']

In [12]:
features_valid = df_valid.drop('is_ultra', axis = 1)
target_valid = df_valid['is_ultra']

In [13]:
from sklearn.dummy import DummyClassifier
dummy = DummyClassifier(strategy='most_frequent').fit(features, target)
baseline = accuracy_score(target_valid, dummy.predict(features_valid))
baseline

0.6936236391912908

Перекос 69/31 означает, что accuracy сама по себе неинформативна и любую модель надо сравнивать с константой 0,694

## Тест Моделей

### Деревья

In [14]:
from sklearn.tree import DecisionTreeClassifier


In [15]:
best_depth = 0
best_result  = 0
for depth in range(1, 11):
    tree = DecisionTreeClassifier(random_state=12345, max_depth=depth) 
    tree.fit(features, target) 
    predictions = tree.predict(features_valid) 
    result = accuracy_score(target_valid, predictions) 
    if result > best_result:
        best_depth = depth
        best_result = result
         
    print(f"max_depth: {depth}, accuracy: {result}")
print()
print(f"best_depth: {best_depth}, accuracy: {best_result}")

max_depth: 1, accuracy: 0.7480559875583204
max_depth: 2, accuracy: 0.7853810264385692
max_depth: 3, accuracy: 0.7993779160186625
max_depth: 4, accuracy: 0.7838258164852255
max_depth: 5, accuracy: 0.7962674961119751
max_depth: 6, accuracy: 0.7978227060653188
max_depth: 7, accuracy: 0.7822706065318819
max_depth: 8, accuracy: 0.7791601866251944
max_depth: 9, accuracy: 0.7822706065318819
max_depth: 10, accuracy: 0.7822706065318819

best_depth: 3, accuracy: 0.7993779160186625


### Леса

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
best_n = 0
best_resualt_2 = 0
best_depth_2 = 0
for n in [10, 20, 30, 40, 50]:
    for depth_2 in range(1, 11):
        forest = RandomForestClassifier(random_state=12345, n_estimators=n, max_depth=depth_2) 
        forest.fit(features, target) 
        predictions_valid_forest = forest.predict(features_valid) 
        result_2 =  accuracy_score(target_valid, predictions_valid_forest)
        if result_2 > best_resualt_2:
            best_resualt_2 = result_2
            best_n = n
            best_depth_2 = depth_2
            best_resualt_2 = result_2
        print(f"depth: {depth_2}, n: {n}, accuracy: {result_2}")   
print(f"best_depth: {best_depth_2}")
print(f"best_n: {best_n}")    
print(f"best_resualt: {best_resualt_2}")    

depth: 1, n: 10, accuracy: 0.7511664074650077
depth: 2, n: 10, accuracy: 0.7667185069984448


depth: 3, n: 10, accuracy: 0.7822706065318819
depth: 4, n: 10, accuracy: 0.7900466562986003
depth: 5, n: 10, accuracy: 0.807153965785381
depth: 6, n: 10, accuracy: 0.8055987558320373
depth: 7, n: 10, accuracy: 0.8102643856920684


depth: 8, n: 10, accuracy: 0.8102643856920684
depth: 9, n: 10, accuracy: 0.8087091757387247


depth: 10, n: 10, accuracy: 0.7978227060653188
depth: 1, n: 20, accuracy: 0.744945567651633
depth: 2, n: 20, accuracy: 0.7838258164852255
depth: 3, n: 20, accuracy: 0.7993779160186625


depth: 4, n: 20, accuracy: 0.7947122861586314
depth: 5, n: 20, accuracy: 0.807153965785381


depth: 6, n: 20, accuracy: 0.8133748055987559
depth: 7, n: 20, accuracy: 0.8087091757387247
depth: 8, n: 20, accuracy: 0.8118195956454122


depth: 9, n: 20, accuracy: 0.8133748055987559
depth: 10, n: 20, accuracy: 0.8164852255054432


depth: 1, n: 30, accuracy: 0.744945567651633
depth: 2, n: 30, accuracy: 0.7822706065318819
depth: 3, n: 30, accuracy: 0.7993779160186625


depth: 4, n: 30, accuracy: 0.7993779160186625


depth: 5, n: 30, accuracy: 0.8087091757387247
depth: 6, n: 30, accuracy: 0.8195956454121306
depth: 7, n: 30, accuracy: 0.8164852255054432


depth: 8, n: 30, accuracy: 0.8164852255054432


depth: 9, n: 30, accuracy: 0.8164852255054432
depth: 10, n: 30, accuracy: 0.8164852255054432


depth: 1, n: 40, accuracy: 0.744945567651633


depth: 2, n: 40, accuracy: 0.7853810264385692
depth: 3, n: 40, accuracy: 0.7978227060653188
depth: 4, n: 40, accuracy: 0.7993779160186625


depth: 5, n: 40, accuracy: 0.8040435458786936


depth: 6, n: 40, accuracy: 0.8149300155520995
depth: 7, n: 40, accuracy: 0.8164852255054432


depth: 8, n: 40, accuracy: 0.8195956454121306


depth: 9, n: 40, accuracy: 0.8164852255054432
depth: 10, n: 40, accuracy: 0.8164852255054432


depth: 1, n: 50, accuracy: 0.7729393468118196


depth: 2, n: 50, accuracy: 0.7838258164852255
depth: 3, n: 50, accuracy: 0.7978227060653188


depth: 4, n: 50, accuracy: 0.8009331259720062


depth: 5, n: 50, accuracy: 0.80248833592535


depth: 6, n: 50, accuracy: 0.8180404354587869


depth: 7, n: 50, accuracy: 0.8180404354587869


depth: 8, n: 50, accuracy: 0.8164852255054432


depth: 9, n: 50, accuracy: 0.8195956454121306


depth: 10, n: 50, accuracy: 0.8180404354587869
best_depth: 6
best_n: 30
best_resualt: 0.8195956454121306


In [18]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=12345, solver='lbfgs', max_iter=1000) 
model.fit(features, target) 

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",12345
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mu

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(StandardScaler(), LogisticRegression(random_state=12345))

In [20]:
pipe.fit(features, target) 

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('standardscaler', ...), ('logisticregression', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some 

In [21]:
predictions_pipe = pipe.predict(features_valid)
accuracy_pipe = accuracy_score(target_valid, predictions_pipe)

predictions_logistic = model.predict(features_valid)
accuracy_logistic = accuracy_score(target_valid, predictions_logistic)

print(f'accuracy_pipe: {accuracy_pipe}')
print(f'accuracy_logistic: {accuracy_logistic}')


accuracy_pipe: 0.7371695178849145
accuracy_logistic: 0.7371695178849145


 Несколько конфигураций дали неразличимый результат и выбрана самая экономная.
 Более точной моделью оказался случайный лес с глубиной 6 и 30 деревьями

In [22]:
print(f'доля предсказанных «Ультра» на валидации: { predictions_pipe.mean()}')

доля предсказанных «Ультра» на валидации: 0.06531881804043546


In [23]:
print(f'реальная доля «Ультра» на валидации  : { target_valid.mean()}')

реальная доля «Ультра» на валидации  : 0.30637636080870917


In [24]:
baseline

0.6936236391912908

In [25]:
data = [['best_depth: 3', 0.7993779160186625, 0.7993779160186625-baseline], 
    ['best_depth: 6, best_n: 30', 0.8195956454121306, 0.8195956454121306-baseline],
    ['max_iter=1000', 0.7371695178849145, 0.7371695178849145-baseline]]

sverka = pd.DataFrame(data, columns=['гиперпараметры', 'accuracy на валидации', 'над базовым уровнем'], index = ['tree', 'forest', 'logistic'])
sverka

,гиперпараметры,accuracy на валидации,над базовым уровнем
tree,best_depth: 3,0.799378,0.105754
forest,"best_depth: 6, best_n: 30",0.819596,0.125972
logistic,max_iter=1000,0.737170,0.043546


Лучшей моделью стал случайный лес с параметрами best_depth: 6, best_n: 30, обходит константу на 0.125972. логистическая регрессия провалилась потому что она пошла по простому пути и просто начала относить к максимальному классу. Она не ищет скрытых зависимостей.

## Переобучение и проверка лучшей модели

In [26]:
new_data = pd.concat([df_train, df_valid])
new_features = new_data.drop('is_ultra', axis = 1)
new_target =   new_data['is_ultra']

In [27]:
features_test = df_test.drop('is_ultra', axis = 1)
target_test = df_test['is_ultra']

In [28]:
dummy_2 = DummyClassifier(strategy='most_frequent').fit(new_features, new_target)
baseline_2 = accuracy_score(target_test, dummy_2.predict(features_test))
baseline_2

0.6936236391912908

In [29]:
best_forest =  RandomForestClassifier(random_state=12345, n_estimators=30, max_depth=6) 

In [30]:
best_forest.fit(new_features, new_target)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",30
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",6
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric(y_t

In [31]:
predictions_test = best_forest.predict(features_test)


In [32]:
best_accuracy_2 = accuracy_score(target_test, predictions_test)

In [33]:
best_accuracy_2

0.8180404354587869

In [34]:
best_accuracy_2 - baseline_2

0.12441679626749613

Модель прошла порог в 0,75
Обходит константу на 12 процентных пункта
Чуть-чуть разошлась с валидационной оценкой но в шум заходит

## Дополнительные метрики логистической регрессии

Accuracy не показывает, что модель почти не находит редкий класс. Считаем recall и precision по «Ультра».

In [35]:
from sklearn.metrics import recall_score, precision_score
print('recall по «Ультра»:', recall_score(target_valid, predictions_pipe))
print('precision по «Ультра»:', precision_score(target_valid, predictions_pipe))
print('нашёл Ультра:', ((predictions_pipe==1) & (target_valid==1)).sum(), 'из', target_valid.sum())

recall по «Ультра»: 0.17766497461928935


precision по «Ультра»: 0.8333333333333334
нашёл Ультра: 35 из 197


## Общий вывод

**Задача.** Оператор «Мегалайн» хочет автоматически предлагать клиентам
с архивных тарифов один из двух актуальных — «Смарт» или «Ультра».
В распоряжении было поведение 3214 клиентов за месяц: количество звонков,
суммарные минуты, число сообщений и израсходованный трафик. Нужна модель
классификации с долей правильных ответов не ниже 0,75.

**Как проверялось качество.** Данные разделены на три части в пропорции
60/20/20 со стратификацией по целевому признаку. Гиперпараметры всех моделей
подбирались на валидационной выборке; тестовая выборка не использовалась
до самого конца и была задействована ровно один раз — для замера итоговой
модели. Финальная модель переобучена на обучающей и валидационной выборках
вместе.

**Точка отсчёта.** Классы распределены неравномерно: 69% клиентов на «Смарт»,
31% на «Ультра». Поэтому доля правильных ответов сама по себе неинформативна:
модель, которая всем без разбора советует «Смарт», получает 0,694, не
анализируя ничего. Все результаты ниже сравниваются именно с этим уровнем.

**Результат.** Лучшей оказалась модель случайного леса — 30 деревьев,
максимальная глубина 6. На тестовой выборке она даёт **0,818** против **0,694**
у константного правила, то есть выигрывает **12,4 процентных пункта**.
В переводе на клиентов: из каждых 100 верную рекомендацию получат около 82
против 69 при простейшем правиле — примерно 13 дополнительных клиентов
на каждую сотню. Порог 0,75 пройден с запасом.

Расхождение с валидационной оценкой (0,820) составило 0,2 процентных пункта
при стандартной ошибке около 1,6 — то есть результат воспроизвёлся.

**Сравнение моделей.**

| модель | accuracy на валидации | над константой |
|---|---:|---:|
| случайный лес (30 деревьев, глубина 6) | 0,820 | +12,6 |
| решающее дерево (глубина 3) | 0,799 | +10,6 |
| логистическая регрессия | 0,737 | +4,4 |

Логистическая регрессия фактически провалилась, и это стоит объяснить.
Она отнесла к «Ультра» лишь 6,5% клиентов при реальной доле 31%: из 197
пользователей «Ультра» в валидационной выборке она нашла 35. При этом
из тех, кого она всё же назвала «Ультра», права она в 83% случаев. То есть
модель научилась узнавать только самые очевидные случаи — клиентов
с экстремально высоким трафиком и разговором, — а всех остальных на всякий
случай относит к большинству. Её accuracy 0,737 выглядит приемлемо ровно
потому, что «относить всех к большинству» на таких данных и есть выигрышная
стратегия по этой метрике.

Причина в устройстве модели: логистическая регрессия проводит одну прямую
границу между классами, а «Ультра» и «Смарт» в этих четырёх признаках так
не разделяются. Дерево и лес строят границу из множества условий и потому
улавливают сочетания признаков, недоступные линейной модели.

Несколько конфигураций леса дали статистически неразличимый результат
(разброс в пределах 0,3 п.п. при стандартной ошибке 1,6 п.п.) — из них
выбрана самая экономная по вычислениям.

**Ограничения.**

1. Accuracy не различает типы ошибок. Предложить «Смарт» тому, кому нужен
   «Ультра», и наоборот — разные потери для оператора, а метрика считает их
   одинаковыми. Прежде чем внедрять, стоит договориться с заказчиком о цене
   каждой из двух ошибок и перейти на метрику, которая её учитывает.
2. Признаков всего четыре, и они сильно связаны между собой: звонки и минуты
   описывают почти одно и то же. Потолок качества на таких данных невысок.
3. Различия между близкими конфигурациями лежат в пределах шума — выбор
   «лучшей» модели с точностью до третьего знака здесь не имеет смысла.

**Что дальше.** Главное, чего не хватает для практической пользы, — цены
тарифов и суммы, которую клиент фактически платит. Модель сейчас угадывает,
каким тарифом клиент пользуется, а бизнес-вопрос другой: какой тариф ему
выгоднее предложить. Это разные задачи, и вторая требует данных о деньгах,
а не только о поведении.